apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq01
  labels:
    app: vprormq01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprormq01
  template:
    labels:
      app: vprormq01
    spec:
      containers:
        - image: vprormq01
          name: rabbitmq
          ports:
            - name: vprormq01-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
